// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See LICENSE in the project root for license information.

#pragma once

import "Media.Capture.idl";
import "Media.PayloadHandler.idl";

namespace CameraCapture.Media.Capture
{
    [version(1.0)]
    [marshaling_behavior(agile)]
    [threading(both)]
    runtimeclass Sink : CameraCapture.Media.IPayloadHandler, Windows.Media.IMediaExtension
    {
        Sink(Windows.Media.MediaProperties.MediaEncodingProfile encodingProfile);

        HRESULT OnEndOfStream();

        State State { get; };
        CameraCapture.Media.PayloadHandler PayloadHandler { get; set; };
        Windows.Media.MediaProperties.MediaEncodingProfile EncodingProfile{ get; };
    };
}
