#pragma once

import "Media.Capture.Payload.idl";

namespace CameraCapture.Media.Capture
{
    [version(1.0)]
    [marshaling_behavior(agile)]
    [threading(both)]
    runtimeclass AudioPayload : Payload
    {
        AudioPayload();

        Windows.Media.MediaProperties.AudioEncodingProperties AudioProperties { get; };
    };
}
