// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See LICENSE in the project root for license information.

#pragma once

namespace CameraCapture.Media.Capture
{
	[version(1.0)]
	enum PayloadType
	{
		Unknown,
		Audio,
		Video,
		Data
	};

	[threading(both)]
	[marshaling_behavior(agile)]
	[version(1.0)]
	runtimeclass Payload
	{
		Payload(Windows.Media.MediaProperties.IMediaEncodingProperties encodingProperties);

		CameraCapture.Media.Capture.PayloadType Type{ get; };
		Windows.Media.MediaProperties.IMediaEncodingProperties EncodingProperties{ get; };
		Windows.Media.Core.MediaStreamSample MediaStreamSample{ get; };
	}
}
